CREATE SCHEMA IF NOT EXISTS flight;
USE flight;

DROP TABLE IF EXISTS passengers;
DROP TABLE IF EXISTS bookings;
DROP TABLE IF EXISTS flights;
DROP TABLE IF EXISTS destinations;

CREATE TABLE IF NOT EXISTS destinations
(
    id         INT AUTO_INCREMENT PRIMARY KEY,
    name       VARCHAR(100) NOT NULL UNIQUE,
    is_enabled BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS flights
(
    id          BIGINT AUTO_INCREMENT PRIMARY KEY,
    datetime    DATETIME     NOT NULL,
    destination VARCHAR(255) NOT NULL,
    empty_seats INT          NOT NULL,
    is_enabled  BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at  DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS bookings
(
    id         BIGINT AUTO_INCREMENT PRIMARY KEY,
    flight_id  BIGINT   NOT NULL,
    tickets    INT      NOT NULL,
    FOREIGN KEY (flight_id) REFERENCES flights (id) ON DELETE CASCADE,
    is_enabled BOOLEAN  NOT NULL DEFAULT TRUE,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS passengers
(
    id         BIGINT AUTO_INCREMENT PRIMARY KEY,
    booking_id BIGINT       NOT NULL,
    full_name  VARCHAR(100) NOT NULL,
    FOREIGN KEY (booking_id) REFERENCES bookings (id) ON DELETE CASCADE,
    is_enabled BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);